# **Comprehensive NLP Lab: From Preprocessing to Feature Extraction**

In this lab, you will explore a wide range of Natural Language Processing (NLP) techniques, from basic text preprocessing to advanced feature extraction and analysis. By the end of this lab, you will be able to:

1. **Tokenize** and preprocess text data.
2. Remove **stop words** and **punctuation**.
3. Apply **stemming** and **lemmatization**.
4. Extract features using **Bag of Words (BoW)** and **TF-IDF**.
5. Generate **n-grams** to capture contextual information.
6. Evaluate the impact of different preprocessing techniques on text data.

Let's dive in!

## **1. Setup the Environment**


Before we begin, ensure you have the necessary libraries installed. Run the following cell to install them:


In [1]:
%pip install nltk scikit-learn pandas matplotlib


Note: you may need to restart the kernel to use updated packages.


Now, import the required libraries:

In [2]:

import nltk
import re
import string
import pandas as pd
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [3]:
# Download NLTK datasets
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')



[nltk_data] Downloading package punkt to
[nltk_data]     /Users/franromlob/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/franromlob/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/franromlob/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/franromlob/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/franromlob/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/franromlob/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

## **2. Text Preprocessing**

### **Exercise 1: Tokenization and Stop Word Removal**

Tokenize the following text

In [4]:
text = ["Natural Language Processing (NLP) is a fascinating field of study! It involves analyzing and understanding human language."]

# your code here
tokenized_docs = [word_tokenize(doc) for doc in text]
for doc in tokenized_docs:
  print(doc)


['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'fascinating', 'field', 'of', 'study', '!', 'It', 'involves', 'analyzing', 'and', 'understanding', 'human', 'language', '.']


Remove stop words and store the result in a variable called `filtered_tokens`

In [43]:
stop_words = set(stopwords.words('english'))

# your code here
print(stop_words)
filtered_tokens = []
filtered_tokens = [word for doc in tokenized_docs 
                   for word in doc 
                   if word not in stop_words]
print("Filtered Tokens:", filtered_tokens)

{'ve', 'yourself', 't', 'd', "she'd", "they've", 'll', 'yours', 'hasn', "needn't", 'as', "they're", 'which', 'with', "he's", 'the', 'just', 'wasn', "we'll", 'same', 'off', 'himself', 'isn', "you've", 'an', 'itself', "shan't", 'whom', "wouldn't", 'yourselves', "i've", 'if', 'how', 'my', 'these', 'too', 'he', 'by', "don't", "we're", 'no', 'who', "mustn't", "won't", 'above', 'it', 'did', 'or', "isn't", 'haven', 'were', "he'll", 'all', 'other', "we've", 'in', 'wouldn', 'her', 'under', 'own', "hadn't", 'very', 'have', 'between', 'won', 'once', 'she', 'so', 'for', "i'd", 'nor', 'hadn', "they'd", "it'd", 'shan', 'until', 'again', 'those', "doesn't", 'doing', 'not', 'are', 'such', 'that', 'them', 'your', 'than', 'him', 'most', "should've", 'm', 'of', "hasn't", 'you', 'each', "it'll", 'me', 'against', 'his', 'here', 'from', "he'd", 'couldn', 'o', 'below', 'y', 'few', "she's", 'through', "we'd", 'was', 'when', 'after', 'only', "she'll", "that'll", 'why', 'has', 'up', "you're", 'ourselves', 'abou

### **Exercise 2: Stemming and Lemmatization**

Apply stemming and lemmatization to the `filtered_tokens`. Compare the results.

In [6]:
porter   = PorterStemmer()
wordnet_lemma  = WordNetLemmatizer()


Apply stemming and store the result in `stemmed_tokens`

In [7]:
# your code here
stemmed_tokens = []

for word in filtered_tokens:
  print("---- ",word,"----")
  print('PS:', porter.stem(word))
  stemmed_tokens.append(porter.stem(word))
stemmed_tokens

----  Natural ----
PS: natur
----  Language ----
PS: languag
----  Processing ----
PS: process
----  ( ----
PS: (
----  NLP ----
PS: nlp
----  ) ----
PS: )
----  fascinating ----
PS: fascin
----  field ----
PS: field
----  study ----
PS: studi
----  ! ----
PS: !
----  It ----
PS: it
----  involves ----
PS: involv
----  analyzing ----
PS: analyz
----  understanding ----
PS: understand
----  human ----
PS: human
----  language ----
PS: languag
----  . ----
PS: .


['natur',
 'languag',
 'process',
 '(',
 'nlp',
 ')',
 'fascin',
 'field',
 'studi',
 '!',
 'it',
 'involv',
 'analyz',
 'understand',
 'human',
 'languag',
 '.']

In [8]:
print("Stemmed Tokens:", stemmed_tokens)

Stemmed Tokens: ['natur', 'languag', 'process', '(', 'nlp', ')', 'fascin', 'field', 'studi', '!', 'it', 'involv', 'analyz', 'understand', 'human', 'languag', '.']


Apply lemmatization and store the result in `lemmatized_tokens`

In [16]:
# your code here
lemmatized_tokens = []

for word in filtered_tokens:
  lemmatized_tokens.append(wordnet_lemma.lemmatize(word, pos='v'))

print("Lemmatized Tokens:", lemmatized_tokens)


Lemmatized Tokens: ['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'fascinate', 'field', 'study', '!', 'It', 'involve', 'analyze', 'understand', 'human', 'language', '.']


## **3. Feature Extraction**

### **Exercise 3: Bag of Words (BoW)**

Use the `CountVectorizer` from `scikit-learn` to create a Bag of Words representation of the following corpus

In [17]:
corpus = [
    "I love NLP.",
    "NLP is amazing.",
    "I enjoy learning new things in NLP."
]

In [18]:

# your code here
# Step 1: Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Step 2: Fit and transform the corpus into a BoW representation
X = vectorizer.fit_transform(corpus)


In [19]:
print("Bag of Words:\n", X.toarray())
print("Vocabulary:", vectorizer.get_feature_names_out())

Bag of Words:
 [[0 0 0 0 0 1 0 1 0]
 [1 0 0 1 0 0 0 1 0]
 [0 1 1 0 1 0 1 1 1]]
Vocabulary: ['amazing' 'enjoy' 'in' 'is' 'learning' 'love' 'new' 'nlp' 'things']


### **Exercise 4: TF-IDF**

Use the `TfidfVectorizer` from `scikit-learn` to create a TF-IDF representation of the same corpus. Store the result in `X_tfidf`

In [28]:
# your code here
import numpy as np

# Step 1: Initialize the TfidfVectorizer
tf_idf_vectorizer = TfidfVectorizer(min_df=1)

# Step 2: Fit and transform the corpus into a TF-IDF representation
X_tfidf = tf_idf_vectorizer.fit_transform(corpus)

for doc, tf_idf_doc in zip(corpus, X_tfidf.todense()):
  print('DOC:', doc)
  print(np.around(tf_idf_doc, 3))
  print()

print("The dictionary contains:", len(tf_idf_vectorizer.vocabulary_), "words")
print(tf_idf_vectorizer.vocabulary_)

DOC: I love NLP.
[[0.    0.    0.    0.    0.    0.861 0.    0.509 0.   ]]

DOC: NLP is amazing.
[[0.652 0.    0.    0.652 0.    0.    0.    0.385 0.   ]]

DOC: I enjoy learning new things in NLP.
[[0.    0.432 0.432 0.    0.432 0.    0.432 0.255 0.432]]

The dictionary contains: 9 words
{'love': 5, 'nlp': 7, 'is': 3, 'amazing': 0, 'enjoy': 1, 'learning': 4, 'new': 6, 'things': 8, 'in': 2}


In [29]:
print("TF-IDF:\n", X_tfidf.toarray())
print("Vocabulary:", tf_idf_vectorizer.get_feature_names_out())

TF-IDF:
 [[0.         0.         0.         0.         0.         0.861037
  0.         0.50854232 0.        ]
 [0.65249088 0.         0.         0.65249088 0.         0.
  0.         0.38537163 0.        ]
 [0.         0.43238509 0.43238509 0.         0.43238509 0.
  0.43238509 0.2553736  0.43238509]]
Vocabulary: ['amazing' 'enjoy' 'in' 'is' 'learning' 'love' 'new' 'nlp' 'things']


### **Exercise 5: N-grams**

Generate `bigrams (2-grams)` from the corpus using `CountVectorizer`. Store the result in `X_bigram`

In [38]:
# your code here
from nltk.util import bigrams
# Step 1: Initialize the CountVectorizer with ngram_range=(2, 2)
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
# Step 2: Fit and transform the corpus into a bigram representation
X_bigram = bigram_vectorizer.fit_transform(corpus)

In [39]:
print("Bigrams:\n", X_bigram.toarray())
print("Bigram Vocabulary:", bigram_vectorizer.get_feature_names_out())

Bigrams:
 [[0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0]
 [1 1 0 1 0 1 0 1]]
Bigram Vocabulary: ['enjoy learning' 'in nlp' 'is amazing' 'learning new' 'love nlp'
 'new things' 'nlp is' 'things in']


## **4. Advanced Exercise: Custom Preprocessing Pipeline**

### **Exercise 6: Build a Custom Preprocessing Pipeline**

Combine all the preprocessing steps (tokenization, stop word removal, punctuation removal, stemming/lemmatization) into a single function. 

In [75]:
# your code here
def text_preprocessing_pipeline(text):
    # Step 1: Tokenize the text
    tokenized_docs = word_tokenize(text)

    # Step 2: Remove stop words
    stop_words = set(stopwords.words('english'))
    print(stop_words)

    tokenized_docs = [word for word in tokenized_docs 
                        if word not in stop_words]
    print("Filtered Tokens:", tokenized_docs)

    # Step 3: Remove punctuation
    pattern = re.compile('[%s]' % re.escape(string.punctuation))
    tokenized_docs_no_punctuation = []
    for token in tokenized_docs:
        new_token = pattern.sub(u'', token)
        if not new_token == u'':
            tokenized_docs_no_punctuation.append(new_token)
    print(tokenized_docs_no_punctuation)

    # Step 4: Apply lemmatization
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(word, pos='v') for word in tokenized_docs_no_punctuation]

    return lemmatized_tokens


Apply this function to the following text

In [76]:
text = "Natural Language Processing (NLP) is a fascinating field of study! It involves analyzing and understanding human language."

# your code here
processed_text = text_preprocessing_pipeline(text)

{'ve', 'yourself', 't', 'd', "she'd", "they've", 'll', 'yours', 'hasn', "needn't", 'as', "they're", 'which', 'with', "he's", 'the', 'just', 'wasn', "we'll", 'same', 'off', 'himself', 'isn', "you've", 'an', 'itself', "shan't", 'whom', "wouldn't", 'yourselves', "i've", 'if', 'how', 'my', 'these', 'too', 'he', 'by', "don't", "we're", 'no', 'who', "mustn't", "won't", 'above', 'it', 'did', 'or', "isn't", 'haven', 'were', "he'll", 'all', 'other', "we've", 'in', 'wouldn', 'her', 'under', 'own', "hadn't", 'very', 'have', 'between', 'won', 'once', 'she', 'so', 'for', "i'd", 'nor', 'hadn', "they'd", "it'd", 'shan', 'until', 'again', 'those', "doesn't", 'doing', 'not', 'are', 'such', 'that', 'them', 'your', 'than', 'him', 'most', "should've", 'm', 'of', "hasn't", 'you', 'each', "it'll", 'me', 'against', 'his', 'here', 'from', "he'd", 'couldn', 'o', 'below', 'y', 'few', "she's", 'through', "we'd", 'was', 'when', 'after', 'only', "she'll", "that'll", 'why', 'has', 'up', "you're", 'ourselves', 'abou

In [77]:
print("Processed Text:", processed_text)

Processed Text: ['Natural', 'Language', 'Processing', 'NLP', 'fascinate', 'field', 'study', 'It', 'involve', 'analyze', 'understand', 'human', 'language']


## **5. Evaluation of Preprocessing Techniques**

### **Exercise 7: Compare Preprocessing Techniques**

Compare the results of stemming and lemmatization on the following sentence. Store the results in `stemmed_tokens` and `lemmatized_tokens`

In [100]:
sentence = "The cats are playing with the mice in the garden."
# your code here
# Step 1: Tokenize and preprocess the sentence and store the result in filtered_tokens
filtered_tokens = word_tokenize(sentence)
# Step 2: Apply stemming
porter = PorterStemmer()
stemmed_tokens = []
for word in filtered_tokens:
  stemmed_tokens.append(porter.stem(word))

# Step 3: Apply lemmatization
wordnet_lemma = WordNetLemmatizer()
lemmatized_tokens = []
for word in stemmed_tokens:
  lemmatized_tokens.append(wordnet_lemma.lemmatize(word))



In [101]:
print("Original Tokens:", filtered_tokens)
print("Stemmed Tokens:", stemmed_tokens)
print("Lemmatized Tokens:", lemmatized_tokens)

Original Tokens: ['The', 'cats', 'are', 'playing', 'with', 'the', 'mice', 'in', 'the', 'garden', '.']
Stemmed Tokens: ['the', 'cat', 'are', 'play', 'with', 'the', 'mice', 'in', 'the', 'garden', '.']
Lemmatized Tokens: ['the', 'cat', 'are', 'play', 'with', 'the', 'mouse', 'in', 'the', 'garden', '.']


## **6. Real-World Dataset: Sentiment Analysis**

### **Exercise 8: Preprocess and Analyze Tweets**

In this exercise, you will work with a real-world dataset of tweets. The dataset contains 5000 positive and 5000 negative tweets. Your task is to preprocess the tweets and extract features for sentiment analysis.


In [102]:
nltk.download('twitter_samples')

[nltk_data] Downloading package twitter_samples to
[nltk_data]     /Users/franromlob/nltk_data...
[nltk_data]   Unzipping corpora/twitter_samples.zip.


True

In [103]:
# Load the dataset
from nltk.corpus import twitter_samples

Load the dataset of positive and negative tweets. 

In [104]:
positive_tweets = twitter_samples.strings('positive_tweets.json')
negative_tweets = twitter_samples.strings('negative_tweets.json')

Combine them into a single list called ``all_tweets`` and create a corresponding list of labels called `labels`.

In [105]:
# your code here

# Combine the datasets
all_tweets = positive_tweets + negative_tweets

# Create labels: 1 for positive, 0 for negative
labels = [1 for _ in positive_tweets] + [0 for _ in negative_tweets]

print(f"Total tweets: {len(all_tweets)}")
print(f"Total labels: {len(labels)}")

Total tweets: 10000
Total labels: 10000


In [ ]:
# Print a sample tweet
print("Sample Tweet:", all_tweets[0])
print("Label:", labels[0])

### **Exercise 9: Preprocess Tweets**

Apply the custom preprocessing pipeline to the entire dataset of tweets. Store the result in ``preprocessed_tweets``.

In [ ]:
# Step 1: Apply the preprocessing pipeline to all tweets
# your code here


In [ ]:
# Print a sample preprocessed tweet
print("Preprocessed Tweets Sample:", preprocessed_tweets[0])

### **Exercise 10: Feature Extraction on Tweets**

Extract features from the preprocessed tweets using **Bag of Words** and **TF-IDF**. Store the results in ``X_bow`` and ``X_tfidf``, respectively.

In [ ]:
# your code here
# Step 1: Create a Bag of Words representation



# Step 2: Create a TF-IDF representation



## **7. Conclusion**

In this lab, you explored a wide range of NLP techniques, from basic text preprocessing to advanced feature extraction and analysis. You also worked with a real-world dataset of tweets and applied your knowledge to preprocess and extract features for sentiment analysis.

